wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717060568
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 7
      - 17
      - 23
      - 37
      - 38
      4: 3.10.0
      5: 0.17.0
      8:
      - 3
      - 5
      10:
      - 3
      13: windows-amd64
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/Precision
      5: 1
      6:
      - 1
    - 1: epoch/Recall
      5: 1
      6:
      - 1
    - 1: epoch/accuracy
      5: 1
      6:
      - 1
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/val_Precision
      5: 1
      6:
      - 1
    - 1: epoch/val_Recall
      5: 1
      6:
      - 1
    - 1: epoch/val_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
