wandb_version: 1

dense_layer_1:
  value: 1024
dense_layer_2:
  value: 256
dense_layer_3:
  value: 64
dense_layer_4:
  value: 32
dropout_rate:
  value: 0.4
epochs:
  value: 50
learning_rate:
  value: 0.0001
