wandb_version: 1

dense_layer_1:
  value: 1024
dense_layer_2:
  value: 512
dense_layer_3:
  value: 64
dense_layer_4:
  value: 64
dropout_rate:
  value: 0.5
epochs:
  value: 200
learning_rate:
  value: 0.0005
