_wandb:
    value:
        cli_version: 0.17.4
        python_version: 3.11.5
        t:
            1:
                - 2
                - 3
                - 5
                - 53
                - 55
            2:
                - 2
                - 3
                - 5
                - 53
                - 55
            3:
                - 2
                - 3
                - 8
                - 23
                - 55
            4: 3.11.5
            5: 0.17.4
            8:
                - 3
                - 5
            10:
                - 9
            12: 0.17.4
            13: windows-amd64
dense_layer_1:
    value: 512
dense_layer_2:
    value: 512
dense_layer_3:
    value: 256
dense_layer_4:
    value: 32
dropout_rate:
    value: 0.3
epochs:
    value: 50
learning_rate:
    value: 0.001
