_wandb:
    value:
        cli_version: 0.17.4
        m:
            - 1: epoch/epoch
              6:
                - 3
            - 1: epoch/accuracy
              5: 1
              6:
                - 1
            - 1: epoch/loss
              5: 1
              6:
                - 1
            - 1: epoch/val_accuracy
              5: 1
              6:
                - 1
            - 1: epoch/val_loss
              5: 1
              6:
                - 1
        python_version: 3.11.5
        t:
            1:
                - 2
                - 3
                - 5
                - 53
                - 55
            2:
                - 2
                - 3
                - 5
                - 53
                - 55
            3:
                - 2
                - 7
                - 23
                - 38
                - 55
            4: 3.11.5
            5: 0.17.4
            8:
                - 3
                - 5
            12: 0.17.4
            13: windows-amd64
dense_layer_1:
    value: 1024
dense_layer_2:
    value: 128
dense_layer_3:
    value: 128
dense_layer_4:
    value: 32
dropout_rate:
    value: 0.3
epochs:
    value: 200
learning_rate:
    value: 0.001
