wandb_version: 1

dense_layer_1:
  value: 512
dense_layer_2:
  value: 128
dense_layer_3:
  value: 64
dense_layer_4:
  value: 64
dropout_rate:
  value: 0.4
epochs:
  value: 50
learning_rate:
  value: 0.0005
