wandb_version: 1

dense_layer_1:
  value: 512
dense_layer_2:
  value: 128
dense_layer_3:
  value: 128
dense_layer_4:
  value: 128
dropout_rate:
  value: 0.5
epochs:
  value: 100
learning_rate:
  value: 0.0005
