wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720764038
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.17.4
      8:
      - 3
      - 5
      13: windows-amd64
